# Generated by Django 5.1.1 on 2024-09-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yield_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvesting_info',
            field=models.TextField(default='no value'),
        ),
        migrations.AddField(
            model_name='crop',
            name='nutritional_requirements',
            field=models.TextField(default='no value'),
        ),
        migrations.AddField(
            model_name='crop',
            name='optimal_conditions',
            field=models.TextField(default='no value'),
        ),
        migrations.AddField(
            model_name='crop',
            name='pest_management',
            field=models.TextField(default='no value'),
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_guidelines',
            field=models.TextField(default='no value'),
        ),
        migrations.AddField(
            model_name='crop',
            name='sustainability_practices',
            field=models.TextField(default='no value'),
        ),
    ]
