# Generated by Django 5.1.1 on 2024-10-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yield_manager', '0002_crop_description_crop_harvesting_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='Region',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='crop',
            name='categories',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='expected_yield',
            field=models.FloatField(default='No description'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='planting_date',
            field=models.DateField(default='No description'),
        ),
    ]
